server:
  port: 8192
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/baloot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update