spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baloot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update