version: '3.4'
services:
  mysql_database:
    image: mysql
    restart: always
    volumes:
      - ./baloot-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=baloot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33061:3306"
    networks:
      - baloot-network

  baloot-app:
    image: baloot:1.0-SNAPSHOT
    restart: always
    environment:
      SPRING_PROFILE: prod
      DB_HOST: "mysql_database"
      DB_PORT: "3306"
    ports:
      - "18888:8192"
      - "8080:8080"
    networks:
      - baloot-network
    depends_on:
      - mysql_database

networks:
  baloot-network: